parameters:
- name: projectName
  type: string
- name: buildConfiguration
  type: string
- name: continueOnError
  type: boolean
  default: false
- name: artifact
  type: string
  default: 'drop'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: Update Assembly version
  continueOnError: ${{ parameters.continueOnError }}
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: Restoring dependencies
  continueOnError: ${{ parameters.continueOnError }}
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Building with Configuration: ${{ parameters.buildConfiguration }}'
  continueOnError: ${{ parameters.continueOnError }}
  condition: succeeded()
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/${{ parameters.projectName }}.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  displayName: Publishing Artifact
  continueOnError: ${{ parameters.continueOnError }}
  artifact: ${{ parameters.artifact }}
