parameters:
- name: vmImage
  type: string

jobs:
- job: SecurityValidating
  displayName: Security Validating
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - task: WhiteSource Bolt@20  # Free License 5 Run / Day
    displayName: Vulnerabilities Scanning    
    condition: |
      or 
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )
        