parameters:
- name: poolImage
  type: string

jobs: 
- job: IntegrationTesting
  displayName: Integration Testing
  pool:
    poolImage: ${{ parameters.poolImage }}
  workspace:
    clean: all
  condition: |
    or
    (
      eq(variables['Build.SourceBranch'], 'refs/heads/master'),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.Reason'], 'Schedule')
    )
  steps:    
  # Building
  - task: DotNetCoreCLI@2
    displayName: 'Building with Configuration: Release'
    inputs:
      projects: '**/*.sln'
      arguments: '--configuration Release'
      