parameters:
- name: vmImage
  type: string
- name: buildConfiguration
  type: string
- name: appName
  type: string
- name: coverageHistoryFeed
  type: string
- name: sonarcloudOrganization
  type: string

jobs:
- job: UnitTesting
  displayName: Unit Testing
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  variables:
  - name  : local#codecoveragehistory.directory
    value : $(Build.ArtifactStagingDirectory)/history
  - name  : local#codecoveragehistory.directory
            # Have to use compile-time expression here to access parameter
    value : ${{ lower(parameters['appName']) }}.$(Build.SourceBranchName)
            #lower( parameters['appName'].variables['Build.SourceBranchName'] )
  - name  : disable.coverage.autogenerate
    value : true
  steps:
  # Preparing
  - task: UniversalPackages@0
    displayName: Getting Test Coverage History
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    continueOnError: true
    inputs:
      command: download
      downloadDirectory: $(local#codecoveragehistory.directory)
      feedsToUse: internal
      vstsFeed: ${{ parameters['coverageHistoryFeed'] }}
      vstsFeedPackage: $(local#codecoveragehistory.directory)
      vstsPackageVersion: 0.*

  - task: SonarCloudPrepare@1
    displayName: Preparing SonarCloud Code Analysis
    condition: |
      or
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )
    inputs:
      SonarCloud: SonarCloud
      organization: $[ parameters['sonarcloudOrganization'] ]
      projectKey: lower(parameters.appName)
      projectName: lower(parameters.appName)
      extraProperties: |
        sonar.coverage.exclusions=**/*[Uu]nit[Tt]ests*/**/*
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml

  # Building
  - task: DotNetCoreCLI@2
    displayName: 'Building with Configuration: ${{ parameters.buildConfiguration }}'
    inputs:
      projects: '**/*.sln'    # The <ProjectGuid> element is not required if you build a solution (sln) containing that project.
                              # for SonarQube
      arguments: '--configuration $(parameters.buildConfiguration)'

  # Testing
  - task: DotNetCoreCLI@2
    displayName: Running Unit Testings
    inputs:
      command: test
      arguments: '--no-build --configuration $(parameters.buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      publishTestResults: true
      projects: '**/*.[Uu]nit[Tt]ests/*.csproj'

  # Generating Coverage Report
  - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
    displayName: Generating Test Coverage Report
    inputs:
      reports: '$(Build.SourcesDirectory)/**/coverage.opencover.xml'
      targetdir: $(Build.SourcesDirectory)/Coverage
      reporttypes: Html;HtmlInline_AzurePipelines_Dark;Cobertura;Badges;SonarQube
      historydir: $(local#codecoveragehistory.directory)

  - task: PublishCodeCoverageResults@1
    displayName: Publishing Test Coverage Report
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/Coverage/Cobertura.xml
      reportDirectory: $(Build.SourcesDirectory)/Coverage

  - task: UniversalPackages@0
    displayName: Saving Test Coverage History
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      command: publish
      publishDirectory: $(local#codecoveragehistory.directory)
      feedsToUsePublish: internal
      vstsFeedPublish: ${{ parameters['coverageHistoryFeed'] }}
      vstsFeedPackagePublish: $(local#codecoveragehistory.directory)
      versionOption: patch
      packagePublishDescription: Code Coverage History for repository $(Build.Repository.Name) on branch $(Build.SourceBranchName)
      verbosity: Information

  - task: SonarCloudAnalyze@1
    displayName: Running SonarCloud Code Analysis
    condition: |
      or
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )

  - task: SonarCloudPublish@1
    displayName: Publishing SonarCloud Analysis Result
    condition: |
      or
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )
