parameters:
- name: vmImage
  type: string

jobs:
- job: StaticTesting
  displayName: Static Testing
  pool:
    vmImage: $[ parameters['vmImage'] ]
  workspace:
    clean: all
  steps:
  # WhiteSource Bolt
  - task: WhiteSource Bolt@20
    displayName: Running WhiteSource Bolt
    # Free License 5 Run / Day
    condition: |
      or 
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )
        