parameters:
- name: poolImage
  type: string

jobs:
- job: StaticTesting
  displayName: Static Testing
  pool:
    poolImage: ${{ parameters["poolImage"] }}
  workspace:
    clean: all
  steps:
  # WhiteSource Bolt
  - task: WhiteSource Bolt@20
    displayName: Running WhiteSource Bolt
    # Free License 5 Run / Day
    condition: |
      or 
      (
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.Reason'], 'PullRequest')
      )
        